### PR TITLE
Don't zero-initialize non-dummy textures

### PR DESCRIPTION
**Pull request by ns6089**
## Description
Follow-up to https://github.com/LizardByte/Sunshine/pull/1098, split up because that pull request is big enough already.
After we start dynamically adjusting capture buffer size, this operation is not free anymore.

## Type of Change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Dependency update (updates to dependencies)
- [ ] Documentation update (changes to documentation)
- [ ] Repository update (changes to repository files, e.g. `.github/...`)

## Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added or updated the in code docstring/documentation-blocks for new or existing methods/components

## Branch Updates
LizardByte requires that branches be up-to-date before merging. This means that after any PR is merged, this branch
must be updated before it can be merged. You must also
[Allow edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [x] I want maintainers to keep my branch updated

### CODE REVIEW

**Comment by cgutman** [comment]
Please rebase your follow-up PRs to remove the commits that are also present in #1098

**Comment by ns6089** [comment]
> Please rebase your follow-up PRs to remove the commits that are also present in #1098

Done.

**Comment by cgutman** [comment]
This looks good to me. Did you leave this in draft state for some reason or can it be merged now?

**Comment by ns6089** [comment]
> This looks good to me. Did you leave this in draft state for some reason or can it be merged now?

Just didn't test it outside of vram branch. Feel free to merge if you think it's good.

**Pull request merged**
