### PR TITLE
chore(l10n): update translations

### PR DESCRIPTION
**Pull request by ReenigneArcher**

### CODE REVIEW

**Comment by lyubomirv** [comment]
Can I ask how should i provide a translation for a new language? Do I go the pull-request way and provide a new json file or is there some translation system in play (like Weblate or something else)?

**Comment by ReenigneArcher** [comment]
@lyubomirv I saw you wanted to request a language, but your comment is now removed and I cannot see your request on CrowdIn either.

Today, I renamed my CrowdIn username to LizardByte and make some tweaks so it's possible that something got lost during that process.

**Comment by lyubomirv** [comment]
@ReenigneArcher I've sent it again on Crowdin. Maybe something was wrong there, so let's see now.

**Comment by ReenigneArcher** [comment]
I think you may have the wrong project? I have no requests.

image

https://translate.lizardbyte.dev is our project.

**Comment by lyubomirv** [comment]
That redirects me to Crowdin when I click on 'Sign in', so I think it should be the same. I added a request using the button 'Request a new language' in the project but maybe that's not the correct way. I've now posted a topic on the Discussions, as you suggest. Let's hope it's more visible now... :)

**Pull request merged**
