### PR TITLE
fix: Reverse Proxy support

### LINKED ISSUE #3008: WebUI can't be used as subpath behind Nginx reverse proxy
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the latest beta/pre-release?

This issue is present in the latest pre-release

### Describe the Bug

When Sunshine is used behind NGINX location it is not working properly because of wrong HREFs/URLs
```
location /sunshine/ {
    auth_request /authelia;
    set $target_url $scheme://$http_host$request_uri;
    auth_request_set $user $upstream_http_remote_user;
    auth_request_set $groups $upstream_http_remote_groups;
    auth_request_set $name $upstream_http_remote_name;
    auth_request_set $email $upstream_http_remote_email;

    proxy_set_header Remote-User $user;
    proxy_set_header Remote-Groups $groups;
    proxy_set_header Remote-Name $name;
    proxy_set_header Remote-Email $email;
    error_page 401 =302 https://auth.xxxxxx.xx/?rd=$target_url;

    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_set_header Host $host;
    proxy_buffering off;
    proxy_pass https://10.10.10.10:47990/;
}
```

### Expected Behavior

_No response_

### Additional Context

Issue is can be fixed by modifying all HTML, CSS, JS by changing **/assets** to **./assets**...   same for all other paths

### Host Operating System

Windows

### Operating System Version

Windows 10

### Architecture

64 bit

### Sunshine commit or version

v2024.808.173930

### Package

Windows - portable

### GPU Type

Nvidia

### GPU Model

RTX 2080

### GPU Driver/Mesa Version

32.0.15.6070

### Capture Method

None

### Config

```Shell
wan_encryption_mode = 0
origin_web_ui_allowed = wan
nvenc_preset = 3
nvenc_spatial_aq = enabled
external_ip = 10.10.10.10
```

### Apps

_No response_

### Relevant log output

```shell
[2024-08-12 14:12:03.798]: Info: Sunshine version: v2024.808.173930
```

### PR DESCRIPTION
**Pull request by Degot**
## Description
These changes allow to use sunshine webui after reverse proxy with subpath.

### Issues Fixed or Closed
- Resolves #3008 

## Type of Change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Dependency update (updates to dependencies)
- [ ] Documentation update (changes to documentation)
- [ ] Repository update (changes to repository files, e.g. `.github/...`)

## Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated the in code docstring/documentation-blocks for new or existing methods/components

### CODE REVIEW

**Comment by ReenigneArcher** [comment]
Thank you for the PR. Please don't remove sections or list entries from the PR template.

https://github.com/LizardByte/.github/blob/master/.github/pull_request_template.md?plain=1

**Comment by Degot** [comment]
> Thank you for the PR. Please don't remove sections or list entries from the PR template.

Do you want me to return original template?

**Comment by ReenigneArcher** [comment]
Yes, please.

**Comment by Degot** [comment]
done

**Comment by B1LL1T3R** [comment]
README.md
Sent from my iPhone

**Comment by ReenigneArcher** [comment]
Perhaps, along with this PR, it would be good to update the docs with a simple example of how to use Sunshine in a reverse proxy? I think it would make sense to go here: https://github.com/LizardByte/Sunshine/blob/master/docs/guides.md , under a new `## General` section.

**Comment by ReenigneArcher** [comment]
> Perhaps, along with this PR, it would be good to update the docs with a simple example of how to use Sunshine in a reverse proxy? I think it would make sense to go here: https://github.com/LizardByte/Sunshine/blob/master/docs/guides.md , under a new `## General` section.

@Degot any thoughts?

**Pull request merged**
