### PR TITLE
Add timers for snapshot/encode in verbose mode

### PR DESCRIPTION
**Pull request by KuleRucket**
## Description
This PR measures the time to snapshot, convert and encode frames and log the information as verbose logging. Although it adds a very small amount of processing when running normally, I find the changes extremely useful for objectively comparing performance between different settings. This can also be useful to diagnose problems when people are not getting the performance we expect.

### Screenshot
n/a

### Issues Fixed or Closed
n/a

## Type of Change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Dependency update (updates to dependencies)
- [ ] Documentation update (changes to documentation)
- [ ] Repository update (changes to repository files, e.g. `.github/...`)

## Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated the in code docstring/documentation-blocks for new or existing methods/components

## Branch Updates
LizardByte requires that branches be up-to-date before merging. This means that after any PR is merged, this branch
must be updated before it can be merged. You must also
[Allow edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [x] I want maintainers to keep my branch updated

### CODE REVIEW

**Comment by KuleRucket** [comment]
Alternatively I could replace the /1000.0 with a cast to milli:
```
auto diff = stop-start;
BOOST_LOG(verbose) << "nvfbc snapshot in "sv << std::chrono::duration <double, std::milli> (diff).count() << "ms"sv;
```

**Comment by KuleRucket** [comment]
What also could be cool is to report the encode time within a sunshine protocol extension so that is can be seen in the client statistics

**Comment by cgutman** [comment]
> What also could be cool is to report the encode time within a sunshine protocol extension so that is can be seen in the client statistics

I think that's probably the right direction to go for this. GFE can send [both small and large frame headers](https://github.com/moonlight-stream/moonlight-common-c/blob/ef9ad529a493d699724d84a189cc1899afcc2d72/src/VideoDepacketizer.c#L845-L856) and right now Moonlight just completely ignores the extra data in the large frame header. We could use some of that space to store a couple of `uint16_t` values in there for capture and encode time.

That would give the client per-frame encode and capture statistics that it can display in the overlay. The problem with logging for performance metrics is that the logging itself can affect performance (and in interesting non-linear ways, like if one particular log message happens to trigger a flush to disk or something).

**Comment by KuleRucket** [comment]
> The problem with logging for performance metrics is that the logging itself can affect performance (and in interesting non-linear ways, like if one particular log message happens to trigger a flush to disk or something).

This is true for end to end performance but what is happening year is that distinct portions are being measured with no logging being performed in between. Measuring the start/end time of an encode then logging the result doesn't affect the time it took to encode.

**Pull request closed without merging**
