### PR TITLE
Create almalinux-9.dockerfile

### PR DESCRIPTION
**Pull request by istori1**
## Description
Add AlmaLinux 9 build.

## Type of Change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Dependency update (updates to dependencies)
- [ ] Documentation update (changes to documentation)
- [ ] Repository update (changes to repository files, e.g. `.github/...`)

## Checklist
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated the in code docstring/documentation-blocks for new or existing methods/components

## Branch Updates
LizardByte requires that branches be up-to-date before merging. This means that after any PR is merged, this branch
must be updated before it can be merged. You must also
[Allow edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [x] I want maintainers to keep my branch updated

### CODE REVIEW

**Comment by ReenigneArcher** [comment]
The fedora rpm doesn't work for this distro?

**Comment by istori1** [comment]
They are not compatible.

sunshine-fedora-38-amd64.rpm                                                                   4.5 MB/s | 6.4 MB     00:01    
Error: 
 Problem: conflicting requests
  - nothing provides boost-filesystem >= 1.78.0 needed by sunshine-0.22.2-1.x86_64 from @commandline
  - nothing provides boost-locale >= 1.78.0 needed by sunshine-0.22.2-1.x86_64 from @commandline
  - nothing provides boost-log >= 1.78.0 needed by sunshine-0.22.2-1.x86_64 from @commandline
  - nothing provides boost-program-options >= 1.78.0 needed by sunshine-0.22.2-1.x86_64 from @commandline
  - nothing provides intel-mediasdk >= 22.3.0 needed by sunshine-0.22.2-1.x86_64 from @commandline
  - nothing provides libX11 >= 1.7.3.1 needed by sunshine-0.22.2-1.x86_64 from @commandline
  - nothing provides libopusenc >= 0.2.1 needed by sunshine-0.22.2-1.x86_64 from @commandline
  - nothing provides libva >= 2.14.0 needed by sunshine-0.22.2-1.x86_64 from @commandline
  - nothing provides libm.so.6(GLIBC_2.35)(64bit) needed by sunshine-0.22.2-1.x86_64 from @commandline
  - nothing provides libstdc++.so.6(GLIBCXX_3.4.30)(64bit) needed by sunshine-0.22.2-1.x86_64 from @commandline
  - nothing provides libstdc++.so.6(GLIBCXX_3.4.32)(64bit) needed by sunshine-0.22.2-1.x86_64 from @commandline
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)

**Comment by ReenigneArcher** [comment]
Okay, this can be considered after #2020.

We're also considering moving Fedora builds to copr. The arm builds just take too long on GitHub (4-5 hours). No idea why the Fedora ones are that slow and Debian ones are only 30-45 minutes.

**Comment by ReenigneArcher** [comment]
It looks like Alma Linux is based on RHEL/CentOS. If we move to copr (quite likely), it will probably be easier to package one of those versus Alma.

**Comment by ReenigneArcher** [comment]
Closing as this will be part of migration to copr builds.

**Pull request closed without merging**
