### PR TITLE
fix path issues

### LINKED ISSUE #60: Can't launch games with the Appimage
### Describe the Bug

Due to the Appimage being setup with the potable home option can not open any games and opening steam creates an entirely new instance of steam. This is due to it using the portable home as our actual home.

### Expected Behavior

to be able to open games :)

### Additional Context

I suggest to move the webserver related stuff back into the app image as we do not need to modify that anyway and turn off the portable home in the building of the app image so it uses our actual home folder so we do not run into this anymore

### Sunshine Host Operating System and Version

Opensuse Tumbleweed

### Architecture

64 bit

### Sunshine Version

0.12.0

### GPU Type

GTX 1660 ti

### CPU Model

Ryzen 1600 AF

### GPU Driver/Mesa Version

510.54

### Capture Method (Linux Only)

_No response_

### LINKED ISSUE #151: Add Sunshine to appimage.github.io
### Describe the Bug

Following the next release of Sunshine; let's add Sunshine to AppImage hub. https://github.com/AppImage/appimage.github.io/pull/2881

### Expected Behavior

_No response_

### Additional Context

This will require that the `sunshine.AppImage` be distributed as a single file instead of an archive. See here: https://github.com/AppImage/appimage.github.io/pull/2881#issuecomment-1120300054

Initially ran into issues attempting to do this with the paths, potentially code changes will be required in sunshine, see here: https://github.com/linuxdeploy/linuxdeploy/issues/201

AppImage suggests that the binary needs to find files relative to itself, which I don't believe is the case, and probably part of the problem. See here: https://docs.appimage.org/packaging-guide/from-source/native-binaries.html?highlight=relative%20path#packaging-existing-binaries-or-manually-packaging-everything

A possible solution is to create a custom `AppRun` file that takes care of copying files out of the AppImage to the expected locations. I'm thinking this could also setup the udev rules. The AppRun can be any type of executable or even a symlink. I'm thinking a bash script would make the most sense.

Another potential solution is to use pkg2AppImage which can patch the sunshine binary, I don't know if it will work in our case. See here: https://docs.appimage.org/packaging-guide/converting-binary-packages/pkg2appimage.html?highlight=apprun#keys-that-enable-ability-to-relocate

### Sunshine Host Operating System and Version

Linux

### Architecture

-

### Sunshine Version

-

### GPU Type

-

### GPU Model

-

### GPU Driver/Mesa Version

-

### Capture Method (Linux Only)

-

### LINKED ISSUE #197: v0.14.0 windows package issues
### Describe the Bug

In https://github.com/SunshineStream/Sunshine/releases/tag/v0.14.0, `install-service.bat` and `uninstall-service.bat` is removed. 

### Expected Behavior

`install-service.bat` and `uninstall-service.bat` should exist

Windows Installer should automatically install the `sunshinevc service`

### Additional Context

https://github.com/SunshineStream/Sunshine/discussions/196

### Sunshine Host Operating System and Version

Windows 11

### Architecture

64 bit

### Sunshine Version

0.14.0

### GPU Type

Nvidia

### GPU Model

GeForce RTX 2070 SUPER

### GPU Driver/Mesa Version

512.95

### Capture Method (Linux Only)

_No response_

### LINKED ISSUE #200: Windows uninstaller does not remove Start Menu shortcut
### Describe the Bug

The start menu shortcut does not get removed on uninstallation of Sunshine:
image
image

### Expected Behavior

It should get removed on uninstallation.

### Additional Context

_No response_

### Sunshine Host Operating System and Version

Windows 11

### Architecture

64 bit

### Sunshine Version

0.14.0

### GPU Type

Nvidia

### GPU Model

GeForce RTX 2070 SUPER

### GPU Driver/Mesa Version

512.95

### Capture Method (Linux Only)

_No response_

### LINKED ISSUE #206: Windows Installer should automatically add and remove firewall rules
### Describe the Bug

#205, but the setup should automatically manage this. Everything should work out of the box.

### Expected Behavior

Windows Installer should automatically add and remove Sunshine firewall rules on installation and uninstallation.

### Additional Context

_No response_

### Sunshine Host Operating System and Version

Windows 11

### Architecture

64 bit

### Sunshine Version

0.14.0

### GPU Type

Nvidia

### GPU Model

GeForce RTX 2070 SUPER

### GPU Driver/Mesa Version

512.95

### Capture Method (Linux Only)

_No response_

### LINKED ISSUE #210: Error Installing RPM 0.14.0 on Fedora Silverblue 36 - '/usr/local' unsupported
### Describe the Bug

When trying to install the rpm for sunshine 0.14.0 on Fedora Silverblue 36 (rpm-ostree install <sunshine.rpm>) I get the error:
```
error: Importing package 'sunshinestream': Analyzing /usr/local: Unsupported path; see https://github.com/projectatomic/rpm-ostree/issues/233
```

### Expected Behavior

RPM should be layered onto my install.

### Additional Context

As Silverblue is an immutable OS it currently doesn't support installing into the /usr/local. You can see the issue here: https://github.com/projectatomic/rpm-ostree/issues/233.

### Sunshine Host Operating System and Version

Fedora Silverblue 36

### Architecture

64 bit

### Sunshine Version

0.14.0

### GPU Type

AMD iGPU + nVIDIA dGPU

### GPU Model

Nvidia RTX 3050

### GPU Driver/Mesa Version

510.68.02

### Capture Method (Linux Only)

Pipewire

### LINKED ISSUE #324: Can't start if $HOME/.config/sunshine folder doesn't exists
### Describe the Bug

Running Sunshine the first time will result in an error.

The problem is that `/home/gr3q/.config/sunshine/` folder doesn't exist, so it fails to copy the config. Manually creating the folder solves the issue.

### Expected Behavior

it should create the folders in the path if they don't exist and then copy the config.

### Additional Context

_No response_

### Host Operating System

Linux

### Operating System Version

Arch Linux

### Architecture

64

### Sunshine Version

0.14.1

### GPU Type

AMD

### GPU Model

RX 580

### GPU Driver/Mesa Version

mesa 22.1.4-1

### Capture Method (Linux Only)

_No response_

### Relevant log output

```Shell
~> sunshine 
terminate called after throwing an instance of 'std::filesystem::__cxx11::filesystem_error'
  what():  filesystem error: cannot copy file: No such file or directory [/usr/share/sunshine/config/sunshine.conf] [/home/gr3q/.config/sunshine/sunshine.conf]
fish: Job 1, 'sunshine' terminated by signal SIGABRT (Abort)
```

### PR DESCRIPTION
**Pull request by ReenigneArcher**
## Description

- move default config and apps files to assets directory
- create appdir if it doesn't exist
- remove backup and restore of config files
- remove portable home and config directories for AppImage
- add service install and uninstall scripts back to Windows packages
- automatically add and remove windows service (if service component is selected at install)
- automatically add and remove firewall rules (if firewall component is selected at install)
- delete start menu entry upon uninstall (Windows only)
- delete program install directory upon uninstall, with user prompt (Windows only)

### Issues Fixed or Closed

- Fixes #60 
- Partially resolves #151 
- Fixes #197 
- Fixes #200 
- Fixes #206 
- Fixes #210 
- Fixes #324 

## Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated the docstring/documentation-blocks for new or existing methods/components

### CODE REVIEW

**Comment by sitiom** [comment]
I currently do not have a Windows machine to test this out, maybe in a few days.

**Comment by ReenigneArcher** [comment]
> I currently do not have a Windows machine to test this out, maybe in a few days.

Okay, just figured I'd ask you to test since you opened those issues/feature requests.

**Comment by sitiom** [comment]
@ReenigneArcher The firewall rule path seems to be wrong, it should be `C:\Program Files\Sunshine\sunshine.exe`:
image

**Comment by ReenigneArcher** [comment]
> @ReenigneArcher The firewall rule path seems to be wrong, it should be `C:\Program Files\Sunshine\sunshine.exe`:
> image
> 

Good catch, I'll take a look at that.

**Comment by ReenigneArcher** [comment]
> The firewall rule path seems to be wrong, it should be `C:\Program Files\Sunshine\sunshine.exe`

This "should" be fixed now.

**Review by sitiom — DISMISSED** [review]

**Pull request merged**
