### PR TITLE
docs: add wayland resolution example

### PR DESCRIPTION
**Pull request by ReenigneArcher**
## Description

Add app example to change display resolution and refresh rate in Linux with Wayland and `wlr-xrandr`.

## Type of Change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Dependency update (updates to dependencies)
- [x] Documentation update (changes to documentation)
- [ ] Repository update (changes to repository files, e.g. `.github/...`)

## Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated the in code docstring/documentation-blocks for new or existing methods/components

## Branch Updates
LizardByte requires that branches be up-to-date before merging. This means that after any PR is merged, this branch
must be updated before it can be merged. You must also
[Allow edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [ ] I want maintainers to keep my branch updated

### CODE REVIEW

**Comment by OlegAckbar** [comment]
Isn't wlr-xrandr only works on wlroots based compositors and will not work on most popular Wayland compositors such as KWin and Mutter?

**Comment by ReenigneArcher** [comment]
> Isn't wlr-xrandr only works on wlroots based compositors and will not work on most popular Wayland compositors such as KWin and Mutter?

I'm not entirely sure. I don't use linux as a daily, but wanted to get some example in for wayland.

**Comment by KarlVogel** [comment]
Something that might be useful, but lutris has an implementation to do resolution switching for gnome/mutter X11/Wayland

https://github.com/lutris/lutris/blob/27cb82afcc80685b3df6fb602986e10f588fd598/lutris/game.py#L859
https://github.com/lutris/lutris/blob/27cb82afcc80685b3df6fb602986e10f588fd598/lutris/util/display.py#L85

**Comment by OlegAckbar** [comment]
> > Isn't wlr-xrandr only works on wlroots based compositors and will not work on most popular Wayland compositors such as KWin and Mutter?
> 
> I'm not entirely sure. I don't use linux as a daily, but wanted to get some example in for wayland.
> 
> According to the manpage on Debian (and other sources), it says it can manage outputs of a Wayland compositor. https://manpages.debian.org/testing/wlr-randr/wlr-randr.1.en.html

Well, indeed it's only supported on wlroots-based compositors which Mutter and KWin aren't, it's even said in description for this utility. Unfortunately, there's no protocol in Wayland for screen managements, so every compositor implementing it themselves.
On KDE you can use kscreen-doctor (part of kscreen)
For example for do I use: kscreen-doctor output.eDP-1.mode.5 (1920x1080@144 for my screen)
for undo: kscreen-doctor output.eDP-1.mode.0 (1280x800@144 use it for my Steam Deck)
Resolution and display mode could be set explicitly
kscreen-doctor output.HDMI-2.mode.1920x1080@60

**Comment by ReenigneArcher** [comment]
> it's even said in description for this utility

@OlegAckbar yes, I should have read the entire description. What's your suggestion then... to remove this example or add additional notes to it?

**Pull request merged**
