### PR TITLE
[Linux Pulse/Pipewire] No sink path

### LINKED ISSUE #226: Crash in PulseAudio init on connecting
### Describe the Bug

I'm using Sunshine in the context of [Games on Whales](https://github.com/games-on-whales/gow).  It's been working great for a while using the older, pre-fork Sunshine, but recently I tried to run with version 0.14.0 and I get a segfault as soon as I try to connect with Moonlight.  I grabbed this stacktrace with gdb:
```
Thread 23 "sunshine-dbg" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffa4804640 (LWP 155)]
0x00007ffff5e15f45 in ?? () from /usr/lib/x86_64-linux-gnu/libc.so.6
(gdb) bt
#0  0x00007ffff5e15f45 in ?? () from /usr/lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff6135589 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator=(char const*) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x0000555555fd1513 in platf::pa::server_t::get_default_sink_name[abi:cxx11]()::{lambda(pa_context*, pa_server_info const*)#1}::operator()(pa_context*, pa_server_info const*) const (
    __closure=0x7fffceffbf20, ctx=0x7fffb4001530, server_info=0x7fffa4803230) at /sunshine/sunshine/platform/linux/audio.cpp:400
#3  0x0000555555fd5e06 in std::__invoke_impl<void, platf::pa::server_t::get_default_sink_name()::{lambda(pa_context*, pa_server_info const*)#1}&, pa_context*, pa_server_info const*>(std::__invoke_other, platf::pa::server_t::get_default_sink_name()::{lambda(pa_context*, pa_server_info const*)#1}&, pa_context*&&, pa_server_info const*&&) (__f=...)
    at /usr/include/c++/10/bits/invoke.h:60
#4  0x0000555555fd5281 in std::__invoke_r<void, platf::pa::server_t::get_default_sink_name()::{lambda(pa_context*, pa_server_info const*)#1}&, pa_context*, pa_server_info const*>(platf::pa::server_t::get_default_sink_name()::{lambda(pa_context*, pa_server_info const*)#1}&, pa_context*&&, pa_server_info const*&&) (__fn=...) at /usr/include/c++/10/bits/invoke.h:110
#5  0x0000555555fd4426 in std::_Function_handler<void (pa_context*, pa_server_info const*), platf::pa::server_t::get_default_sink_name()::{lambda(pa_context*, pa_server_info const*)#1}>::_M_invoke(std::_Any_data const&, pa_context*&&, pa_server_info const*&&) (__functor=..., __args#0=@0x7fffa48031c0: 0x7fffb4001530, __args#1=@0x7fffa48031b8: 0x7fffa4803230)
    at /usr/include/c++/10/bits/std_function.h:291
#6  0x0000555555fd4515 in std::function<void (pa_context*, pa_server_info const*)>::operator()(pa_context*, pa_server_info const*) const (this=0x7fffceffbf20, __args#0=0x7fffb4001530,
    __args#1=0x7fffa4803230) at /usr/include/c++/10/bits/std_function.h:622
#7  0x0000555555fd336d in platf::pa::cb<pa_server_info*> (ctx=0x7fffb4001530, i=0x7fffa4803230, userdata=0x7fffceffbf20) at /sunshine/sunshine/platform/linux/audio.cpp:135
#8  0x00007ffff6220579 in ?? () from /usr/lib/x86_64-linux-gnu/libpulse.so.0
#9  0x00007ffff1ea6df3 in ?? () from /usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-14.2.so
#10 0x00007ffff1ea780f in pa_pdispatch_run () from /usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-14.2.so
#11 0x00007ffff6220873 in ?? () from /usr/lib/x86_64-linux-gnu/libpulse.so.0
#12 0x00007ffff1eab8fd in ?? () from /usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-14.2.so
#13 0x00007ffff1ead48f in ?? () from /usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-14.2.so
#14 0x00007ffff6234603 in pa_mainloop_dispatch () from /usr/lib/x86_64-linux-gnu/libpulse.so.0
#15 0x00007ffff6234c62 in pa_mainloop_iterate () from /usr/lib/x86_64-linux-gnu/libpulse.so.0
#16 0x00007ffff6234d00 in pa_mainloop_run () from /usr/lib/x86_64-linux-gnu/libpulse.so.0
#17 0x0000555555fcfd61 in platf::pa::server_t::init()::{lambda(pa_mainloop*)#2}::operator()(pa_mainloop*) const (__closure=0x7fffb4003a28, loop=0x7fffb4001430)
    at /sunshine/sunshine/platform/linux/audio.cpp:232
#18 0x0000555555fd7560 in std::__invoke_impl<void, platf::pa::server_t::init()::{lambda(pa_mainloop*)#2}, pa_mainloop*>(std::__invoke_other, platf::pa::server_t::init()::{lambda(pa_mainloop*)#2}&&, pa_mainloop*&&) (__f=...) at /usr/include/c++/10/bits/invoke.h:60
#19 0x0000555555fd74bb in std::__invoke<platf::pa::server_t::init()::{lambda(pa_mainloop*)#2}, pa_mainloop*>(platf::pa::server_t::init()::{lambda(pa_mainloop*)#2}&&, pa_mainloop*&&) (
    __fn=...) at /usr/include/c++/10/bits/invoke.h:95
#20 0x0000555555fd741b in std::thread::_Invoker<std::tuple<platf::pa::server_t::init()::{lambda(pa_mainloop*)#2}, pa_mainloop*> >::_M_invoke<0ul, 1ul>(std::_Index_tuple<0ul, 1ul>) (
    this=0x7fffb4003a28) at /usr/include/c++/10/thread:264
#21 0x0000555555fd7376 in std::thread::_Invoker<std::tuple<platf::pa::server_t::init()::{lambda(pa_mainloop*)#2}, pa_mainloop*> >::operator()() (this=0x7fffb4003a28)
    at /usr/include/c++/10/thread:271
#22 0x0000555555fd730e in std::thread::_State_impl<std::thread::_Invoker<std::tuple<platf::pa::server_t::init()::{lambda(pa_mainloop*)#2}, pa_mainloop*> > >::_M_run() (
    this=0x7fffb4003a20) at /usr/include/c++/10/thread:215
#23 0x00007ffff60c7694 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#24 0x00007ffff7fa1450 in start_thread () from /usr/lib/x86_64-linux-gnu/libpthread.so.0
#25 0x00007ffff5dadd53 in clone () from /usr/lib/x86_64-linux-gnu/libc.so.6
```

### Expected Behavior

_No response_

### Additional Context

My `server_info` pointer is apparently non-null but still invalid, because this is the line that's crashing: https://github.com/SunshineStream/Sunshine/blob/70ae7a2fa9b33173eb949c86ec42a96e7b9e8c25/sunshine/platform/linux/audio.cpp#L400.  I haven't done any further digging yet.

### Sunshine Host Operating System and Version

unRAID 6.10.3 / Docker, Dockerfile based on Ubuntu 21.04

### Architecture

64-bit

### Sunshine Version

Built from source at 70ae7a2fa9b33173eb949c86ec42a96e7b9e8c25

### GPU Type

Nvidia

### GPU Model

GeForce GTX 1660 Ti

### GPU Driver/Mesa Version

470.129.06

### Capture Method (Linux Only)

X11

### PR DESCRIPTION
**Pull request by Logical-sh**
## Description
Added some logic so it should handle the case of no default audio sink.
I do not currently have a setup where there are no audio sinks to test this, and am having encoder issues on my current machine, therefore I marked this as draft until further testing can occur.

### Issues Fixed or Closed
- Fixes #226 

## Type of Change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

## Testing Scenarios
- [ ] No sinks on launch (Should create and switch to virtual sink)
- [ ] Has a sink, Uses "play audio on host"
- [ ] Has a sink, Does not use "play audio on host"

### CODE REVIEW

**Comment by zb140** [comment]
I would really like to see this get merged :-) I'm available to help testing the "no sinks on launch" case if it helps.

**Comment by ReenigneArcher** [comment]
> I would really like to see this get merged :-) I'm available to help testing the "no sinks on launch" case if it helps.

This PR is still in a draft state. Once it's marked ready we can build this version to test.

**Comment by zb140** [comment]
Per @ABeltramo's request, I've tested this branch on my setup with no sinks, and it works perfectly. As expected, I see this in the logs when I connect:
```
gow-sunshine-1  | [2022:08:10:17:46:24]: Warning: Couldn't find an active default sink. Continuing with virtual audio only.                                                                
```
So we know it's going through the correct code path.  After connecting, audio plays back correctly with no issues.  Thanks @Logical-sh !

**Comment by ReenigneArcher** [comment]
@zb140 thank you for testing!

@Logical-sh is it possible for you to update your branch with our latest changes? I believe the main thing that changed is the directory of those files changed from `sunshine` to `src`. We also now require that branches are up to date before merging (since I learned about branch protection rules).

**Comment by Sparticuz** [comment]
Is there something blocking the rebase?

**Comment by Logical-sh** [comment]
As far as I know, nothing technical.
I have just recently gotten my main dev pc back online and need to re-setup
all my dev tools and the repository.
I can try to get this sorted out this week!

**Comment by Logical-sh** [comment]
Closing in favor of #372.

**Pull request closed without merging**
