### PR TITLE
feat(apps): order apps alphabetically

### PR DESCRIPTION
**Pull request by ReenigneArcher**
## Description

Sort apps alphabetically.

Original plan was to sort them via the webUI; however the it attempted to delete/edit the incorrect apps due to the change in index order. So opted to alphabetize the `apps.json` before saving the file.

### Issues Fixed or Closed

- Resolves https://github.com/orgs/LizardByte/discussions/489

## Type of Change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Dependency update (updates to dependencies)
- [ ] Documentation update (changes to documentation)
- [ ] Repository update (changes to repository files, e.g. `.github/...`)

## Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated the in code docstring/documentation-blocks for new or existing methods/components

### CODE REVIEW

**Comment by ReenigneArcher** [comment]
@moi952 not in my opinion, no. Also, we don't track app usage so that would be a huge change instead of a simple one.

Anyway, this PR is to address this feature request, nothing more. https://github.com/orgs/LizardByte/discussions/489

**Comment by reloxx13** [comment]
> Hi @ReenigneArcher , wouldn't it be interesting to put recently used apps first? 😜

It orders the apps in the sunshine admin ui, not in streaming clients/moonlight.

**Comment by ReenigneArcher** [comment]
It should technically order it in moonlight clients as well, unless they have their own ordering method.

**Comment by ReenigneArcher** [comment]
Fixed the code smells, and a few others in this file.

**Comment by ReenigneArcher** [comment]
Now depends on https://github.com/LizardByte/Sunshine/pull/3236 due to one of the code smell fixes

**Pull request merged**
