### PR TITLE
fix(linux): use correct value for AMD_DEBUG environment variable

### PR DESCRIPTION
**Pull request by ReenigneArcher**
## Description

Fix typo reported here: https://github.com/LizardByte/Sunshine/commit/bf92fda969367d9dbf427db6669ec012e86b7376#r146064860

## Type of Change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Dependency update (updates to dependencies)
- [ ] Documentation update (changes to documentation)
- [ ] Repository update (changes to repository files, e.g. `.github/...`)

## Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated the in code docstring/documentation-blocks for new or existing methods/components

### CODE REVIEW

**Comment by ReenigneArcher** [comment]
@gschintgen FYI

**Comment by gschintgen** [comment]
> @gschintgen FYI

LGTM. I'll testdrive the 24.04 artifact in a few hours (and check the encoder clock frequencies.)

**Comment by gschintgen** [comment]
> > 
> 
> LGTM. I'll testdrive the 24.04 artifact in a few hours (and check the encoder clock frequencies.)

It's working great:
image
Both frequencies stay high while streaming. (screenshot of `amdgpu_top`)

Initially I was a bit frustrated since I couldn't even get it to work with the earlier pre-release even though I correctly launched it using the AMD_DEBUG variable. I then realized that current master actually prevents lowlatency mode from working, since it unconditionally overwrites a user-provided AMD_DEBUG variable...

Anyway this PR is good news for AMD users.

Sidenote: Ubuntu 24.04 (to which I upgraded last night from the previous LTS) ships with mesa 24.0.9. Not even kisak-stable/turtle PPA is current enough. At the time being Ubuntu 24.04 users will have to install the kisak-fresh PPA. But no other tinkering is necessary.

**Comment by gschintgen** [comment]
Another sidenote: I thought the versioning was changed/fixed. I'm wondering if this is the expected behavior:
```
dpkg: warning: downgrading sunshine from 2024.831.174557 to 0.0.0.6c483429b3819aa07ace4f4b66f2af8fd16ca69f
```
(that's when installing the build artifact of this PR)

**Comment by ReenigneArcher** [comment]
> Another sidenote: I thought the versioning was changed/fixed. I'm wondering if this is the expected behavior:
> 
> ```
> dpkg: warning: downgrading sunshine from 2024.831.174557 to 0.0.0.6c483429b3819aa07ace4f4b66f2af8fd16ca69f
> ```
> 
> (that's when installing the build artifact of this PR)

Pull requests won't get a version number.

**Pull request merged**
