### PR TITLE
build(linux): drop support for AUR

### PR DESCRIPTION
**Pull request by ReenigneArcher**
## Description

Dropping support for ArchLinux AUR as I am not willing to constantly battle people like `@xiota`, `@dr460nf1r3`. No bug reports will be accepted from users using any AUR package.

## Type of Change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Dependency update (updates to dependencies)
- [x] Documentation update (changes to documentation)
- [x] Repository update (changes to repository files, e.g. `.github/...`)

## Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated the in code docstring/documentation-blocks for new or existing methods/components

## Branch Updates
LizardByte requires that branches be up-to-date before merging. This means that after any PR is merged, this branch
must be updated before it can be merged. You must also
[Allow edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [ ] I want maintainers to keep my branch updated

### CODE REVIEW

**Comment by hilts-vaughan** [comment]
Has LizardByte considered setting up their own repository? It would allow more control and less harassment. However, I understand it is easier to simply not support it.

Thanks for at least providing a manual install option. I personally will be removing the AUR package as I can't in good faith trust someone who is willing to usurp a package like that when the upstream maintainer was doing it for so long.

Thanks for everything!

**Comment by ReenigneArcher** [comment]
@hilts-vaughan I was looking into that, although the repo would just be the 2-3 files that are in the new `sunshine.pkg.tar.gz` release asset.

I guess the advantage would be for the user when it comes to updates, so I will try to come up a with a way to do this, and keep things hosted on GitHub. I do see AUR has a [mirror](https://github.com/archlinux/aur) on GitHub, for which it would be super easy to setup an equivalent... but how can a user point to such a repo hosted in GitHub?

There doesn't seem to be much info on the web about hosting a private AUR. Maybe these two tools can help (I need to investigate it a little more).

- https://github.com/pacman-repo-builder/pacman-repo-builder
- https://github.com/pacman-repo-builder/action

**Comment by hilts-vaughan** [comment]
I wish I had more information to offer, sorry. I just consumed a few for a while (AUR helpers used to use them, archlinux.fr had one for some time) Given there is tooling, obviously some people maintain them as well.. but setting up an _entire package repo_ for a few files seems like a lot of work an infrastructure for you to have to maintain.  :(

It's pretty trivial for users to point their CLI tool at a PKGBUILD though -- so even that would be helpful (though again, easy to point it at the artfact too) but without the other repo bits you don't get auto update.

**Comment by ReenigneArcher** [comment]
It looks like it actually won't be all that difficult. Here's an example. https://github.com/KSXGitHub/pacman-repo

I will play with it more in the coming days.

**Comment by ReenigneArcher** [comment]
@hilts-vaughan I have created a self hosted pacman repo, here: https://github.com/LizardByte/pacman-repo

It contains PKGBUILDs and rebuilds packages once a day, so users shouldn't even necessarily need the PKGBUILD anymore.

**Comment by patod01** [comment]
Hi! I've been looking forward the next release since I saw the new feature of naming and deleting clients one by one. I'm a new linux user running away from windows and I chose arch like 5 months ago.

Today I was in this repository again to read the pre-releases notes once again and I just found a "read more" link, then I found out the AUR drama and it made me stare at the horizon for a while after reading all the messages there.

I don't know if this is the best place to write to you, but I just wanted to say thanks for your work. It makes me a bit sad the results of the discussion, but if you're better now, that's great. And, being positive, you motivated me to make my own repo once I learn to program well enough and have some projects! Because, certainly I enjoy pacman way more than apt, so if I change distro in the future, I'll keep using it.

I will be switching to your pacman repo next sunday. Waiting for the next stable release of this project has been like waiting for xmas for me. I can't stop reading the changelog every week. Thanks again and have a nice weekend!

**Comment by ReenigneArcher** [comment]
Thank you. The next stable release will "probably" be coming soon-ish. With that said, beta/pre-releases are usually pretty solid. Beta is also available in https://github.com/LizardByte/pacman-repo

**Pull request merged**
