### PR TITLE
fix(deps): replace libboost chrono and thread with standard chrono and thread

### PR DESCRIPTION
**Pull request by Era-Dorta**
## Description
Sunshine crashes on Ubuntu 22.04 due a missing lib boost dependency. This PR adds the missing dependency for the deb packages.

## Type of Change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Dependency update (updates to dependencies)
- [ ] Documentation update (changes to documentation)
- [ ] Repository update (changes to repository files, e.g. `.github/...`)

## Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added or updated the in code docstring/documentation-blocks for new or existing methods/components

## Branch Updates
LizardByte requires that branches be up-to-date before merging. This means that after any PR is merged, this branch
must be updated before it can be merged. You must also
[Allow edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [x] I want maintainers to keep my branch updated

### CODE REVIEW

**Comment by ReenigneArcher** [comment]
Thank you for the PR. I kind of think the solution is to switch to the standard chrono instead of boost... Unless I'm missing something.

**Comment by Era-Dorta** [comment]
Thanks for lighting fast review. I didn't really look at the code much at first. I just got this error
`sunshine: error while loading shared libraries: libboost_chrono.so.1.74.0: cannot open shared object file: No such file or directory`
and it seemed like the obvious fix.

I now see that the code uses `std:chrono` and not `boost:chrono`. I haven't worked with C++ for a while, so I'm quite rusty at it. Does this mean that the binary somehow got built to link to `libboost` so the build environment for the deb packages is wrong?

**Comment by ReenigneArcher** [comment]
I'm not quite sure how it linked to boost chrono as it's not even installed in the build environment.

https://github.com/LizardByte/Sunshine/blob/master/docker/ubuntu-20.04.dockerfile#L39

There might be a compile warning that doesn't fail the build and it is harder to detect.

But I think boost chrono was just used in 2 files. Probably the solution is to just switch those to standard chrono.

**Comment by Era-Dorta** [comment]
Makes a lot more sense now, I've done as suggested in the last two commits.

**Comment by Era-Dorta** [comment]
It looks like the boost threading doesn't like the std time. I've switched it to use std threading too. After a quick search, it seems like `libboost-thread` can be removed as a dependency, as this was the only place that was used.

**Comment by Era-Dorta** [comment]
Sorry about the crashes with the CI, I've done a manual launch on my fork and it seems to work now https://github.com/Era-Dorta/Sunshine/actions/runs/5248057310

**Comment by Era-Dorta** [comment]
Is there anything else I should do to move this forwards?

**Comment by ReenigneArcher** [comment]
I just need to review it, which might take some time.

There were some ci failures (cancelled) for some reason.

**Comment by Max-Might** [comment]
@ReenigneArcher Do you think this could be released as a hotfix? Version 0.20.0 is broken for a lot of people (me including) because of this issue.

**Comment by ReenigneArcher** [comment]
We don't do hot fixes and this has not been merged yet. You can manually install the missing dependency and sunshine will work fine.

**Review by cgutman — APPROVED** [review]

**Pull request merged**
