### PR TITLE
Use dl handle for libva's vaTerminate rather than actual function

### PR DESCRIPTION
**Pull request by chewi**
## Description
libva is supposed to be optional. Building currently fails with an unresolved symbol if it is missing.

## Type of Change
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Dependency update (updates to dependencies)
- [ ] Documentation update (changes to documentation)
- [ ] Repository update (changes to repository files, e.g. `.github/...`)

## Checklist
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have added or updated the in code docstring/documentation-blocks for new or existing methods/components

## Branch Updates
LizardByte requires that branches be up-to-date before merging. This means that after any PR is merged, this branch
must be updated before it can be merged. You must also
[Allow edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [X] I want maintainers to keep my branch updated

### CODE REVIEW

**Comment by ReenigneArcher** [comment]
> libva is supposed to be optional

How did you come to that conclusion?

**Comment by chewi** [comment]
> > libva is supposed to be optional
> 
> How did you come to that conclusion?

If it was mandatory, you wouldn't load it with `dlopen`. :slightly_smiling_face: I've been packaging Sunshine for Gentoo Linux (more on than later) where do we our own ffmpeg build, and that can optionally be done without VAAPI support. I have successfully built and run Sunshine without any VAAPI support at all.

**Comment by ReenigneArcher** [comment]
> our own ffmpeg build

Please include these patches, if you're not already. https://github.com/LizardByte/build-deps/tree/master/ffmpeg_patches

> without VAAPI support

If you're building without vaapi support... then cmake should probably just be modified to not include the vaapi.cpp source. That's what we do for cuda, drm, wayland, x11

cuda:
https://github.com/LizardByte/Sunshine/blob/nightly/cmake/compile_definitions/linux.cmake#L15-L99

drm:
https://github.com/LizardByte/Sunshine/blob/a6ffeb4b53a6d7a5089d7b4fc0479a9fb575ba5e/cmake/compile_definitions/linux.cmake#L101-L119

wayland:
https://github.com/LizardByte/Sunshine/blob/a6ffeb4b53a6d7a5089d7b4fc0479a9fb575ba5e/cmake/compile_definitions/linux.cmake#L121-L143

x11:
https://github.com/LizardByte/Sunshine/blob/a6ffeb4b53a6d7a5089d7b4fc0479a9fb575ba5e/cmake/compile_definitions/linux.cmake#L145-L156

**Comment by cgutman** [comment]
I think this fix makes sense to take to allow builds that were compiled with VAAPI to be able to run without it present at runtime. It's a niche use case, but if the fix is just changing a single function call, I don't see any problem with it.

For builds without VAAPI, I agree with @ReenigneArcher that we should just not compile any of the VAAPI stuff in at all.

**Comment by ReenigneArcher** [comment]
I'll merge this then, and work on a second PR to allow disabling vaapi with a cmake flag.

**Pull request merged**
