### PR TITLE
Installer option cleanup, manual start option, and service rename

### LINKED ISSUE #1126: Malware Bytes Reports False Positive
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

Malware Bytes currently reports Sunshine as a Potentially Unwanted Program (Corner Sunshine). Apparently, to get it to whitelist you, a dev needs to email pup@malwarebytes.com.

image

### Expected Behavior

_No response_

### Additional Context

_No response_

### Host Operating System

Windows

### Operating System Version

Windows 11

### Architecture

64 bit

### Sunshine commit or version

0.19.1.01167569abfddac195db968ce1da5111b15e6cc7

### Package

Windows - installer

### GPU Type

Nvidia

### GPU Model

3080

### GPU Driver/Mesa Version

531.41

### Capture Method (Linux Only)

_No response_

### Config

```Shell
Irrelevant for this.
```

### Apps

_No response_

### Relevant log output

```shell
Irrelevant for this.
```

### PR DESCRIPTION
**Pull request by cgutman**
## Description
The first commit consolidates required service options and introduces friendly text for each installer option. The text changes ensure the new "Launch on Startup" option doesn't stick out from the others.

The second commit adds a friendly name to be displayed for SunshineSvc in Task Manager and Services.msc. It's totally cosmetic but nice to have.

The third commit introduces a configurable installer option to allow users to select whether they want Sunshine to start on boot (enabled by default as it is today). Some users don't want Sunshine to start automatically, so this allows them to still use the installer version for that use case now that the service is mandatory. If the service isn't running yet, the shortcut launch code elevates itself and starts it.

The fourth commit expands the Core component group by default, since it contains the new "Launch on Startup" option.

The fifth commit renames the service from SunshineSvc to SunshineService to address a false positive from MalwareBytes. The actual binary on disk remains with the same name.

### Screenshot
image

image

### Issues Fixed or Closed
Fixes #1126

## Type of Change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Dependency update (updates to dependencies)
- [ ] Documentation update (changes to documentation)
- [ ] Repository update (changes to repository files, e.g. `.github/...`)

## Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated the in code docstring/documentation-blocks for new or existing methods/components

## Branch Updates
LizardByte requires that branches be up-to-date before merging. This means that after any PR is merged, this branch
must be updated before it can be merged. You must also
[Allow edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [x] I want maintainers to keep my branch updated

### CODE REVIEW

**Review by ReenigneArcher — COMMENTED** [review]
With this change should we expand the groups automatically?

https://cmake.org/cmake/help/latest/module/CPackComponent.html#command:cpack_add_component_group

Might help getting users to install Sunshine how they want.

**Comment by ReenigneArcher** [comment]
I have no objection to renaming. If we do rename, we'll also need to adjust the remove service script so it removes both names.

**Comment by cgutman** [comment]
> Should we go ahead and rename sunshinesvc to sunshinestreamsvc or whatever for this as well?

Yeah, I guess we can do that here too. What do we name it? SunshineStreamService, SunshineStreamSvc, or something else?

> As for auto expanding, seems like a good idea but the installer is a bit too small, not sure if that is easy to fix

I'll expand the Core section. I don't think we generally want users tinkering with the other options.

I'm not sure how to adjust the layout either, but I guess they can scroll manually.

**Comment by ReenigneArcher** [comment]
SunshineStreamService would be my vote.

**Comment by cgutman** [comment]
I ended up going with "SunshineService", since it's a little shorter and SunshineSvc.exe can remain as an abbreviation of "SunshineService". I verified that the MalwareBytes false positive goes away with the new service name without changing the binary name.

Let me know if "SunshineService" is fine or you want "SunshineStreamService" instead.

**Comment by Nonary** [comment]
> I ended up going with "SunshineService", since it's a little shorter and SunshineSvc.exe can remain as an abbreviation of "SunshineService". I verified that the MalwareBytes false positive goes away with the new service name without changing the binary name.
> 
> Let me know if "SunshineService" is fine or you want "SunshineStreamService" instead.

Fine with me, the other name was a bit long

**Review by ReenigneArcher — APPROVED** [review]

**Pull request merged**
