### PR TITLE
add -fPIE to CMAKE flags

### PR DESCRIPTION
**Pull request by matte-schwartz**
## Description

add -fPIE to CMAKE flags for tests in order for builds to not fail on COPR. otherwise compiling the tests throws
```
[100%] Linking CXX executable test_sunshine
<bunch of CMakeFile code>
/usr/bin/ld: CMakeFiles/test_sunshine.dir/ci/test_docs.cpp.o: relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: failed to set dynamic section sizes: bad value
collect2: error: ld returned 1 exit status
make[2]: *** [tests/CMakeFiles/test_sunshine.dir/build.make:926: tests/test_sunshine] Error 1
make[1]: *** [CMakeFiles/Makefile2:271: tests/CMakeFiles/test_sunshine.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
error: Bad exit status from /var/tmp/rpm-tmp.w6rvsS (%build)
```

## Type of Change
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Dependency update (updates to dependencies)
- [ ] Documentation update (changes to documentation)
- [ ] Repository update (changes to repository files, e.g. `.github/...`)

## Checklist
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have added or updated the in code docstring/documentation-blocks for new or existing methods/components

## Branch Updates
LizardByte requires that branches be up-to-date before merging. This means that after any PR is merged, this branch
must be updated before it can be merged. You must also
[Allow edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [ ] I want maintainers to keep my branch updated

### CODE REVIEW

**Comment by ReenigneArcher** [comment]
It seems that the `-fPIE` flag is messing with the coverage results -> https://app.codecov.io/gh/LizardByte/Sunshine/pull/2311/indirect-changes?src=pr&el=tree-more&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=LizardByte

**Comment by matte-schwartz** [comment]
Will look further into it and get back to you on next steps or closing this.

**Comment by istori1** [comment]
Another way to achieve this is by passing `-DCMAKE_POSITION_INDEPENDENT_CODE=ON` to cmake.

**Comment by ReenigneArcher** [comment]
Closing per https://discord.com/channels/804382334370578482/1209573391485501540/1223077245485322293

**Pull request closed without merging**
