### PR TITLE
Input extensions

### LINKED ISSUE #1362: DS5 Trackpad / Share Button not working when emulating DS4
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

While using a DS5 Controller the Share Button and the Trackpad(click & gesture) is not working.

### Expected Behavior

_No response_

### Additional Context

_No response_

### Host Operating System

Windows

### Operating System Version

Windows 11

### Architecture

64 bit

### Sunshine commit or version

0.20

### Package

Windows - installer

### GPU Type

AMD

### GPU Model

RTX 6800

### GPU Driver/Mesa Version

23.5.2

### Capture Method (Linux Only)

_No response_

### Config

```Shell
upnp = enabled
gamepad = ds4
```

### Apps

_No response_

### Relevant log output

```shell
[2023:06:11:12:46:43]: Info: Sunshine version: 0.20.0
[2023:06:11:12:46:43]: Info: Compiling shaders...
[2023:06:11:12:46:43]: Info: System tray created
[2023:06:11:12:46:43]: Info: Compiled shaders
[2023:06:11:12:46:43]: Info: // Testing for available encoders, this may generate errors. You can safely ignore those errors. //
[2023:06:11:12:46:43]: Info: Trying encoder [nvenc]
[2023:06:11:12:46:43]: Info: ddprobe.exe [1] [] returned: 0x00000000
[2023:06:11:12:46:43]: Info: Set GPU preference: 1
[2023:06:11:12:46:43]: Info: 
Device Description : AMD Radeon RX 6800
Device Vendor ID   : 0x00001002
Device Device ID   : 0x000073BF
Device Video Mem   : 16337 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 16262 MiB
Feature Level      : 0x0000B100
Capture size       : 2560x1440
Offset             : 0x0
Virtual Desktop    : 2560x1440
[2023:06:11:12:46:43]: Info: Desktop resolution [2560x1440]
[2023:06:11:12:46:43]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2023:06:11:12:46:43]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 10
Red Primary        : [0.678711,0.314453]
Green Primary      : [0.268555,0.666992]
Blue Primary       : [0.152344,0.0615234]
White Point        : [0.3125,0.329102]
Min Luminance      : 0.0491 nits
Max Luminance      : 603 nits
Max Full Luminance : 351 nits
[2023:06:11:12:46:43]: Info: SDR color coding [Rec. 601]
[2023:06:11:12:46:43]: Info: Color range: [JPEG]
[2023:06:11:12:46:43]: Error: Could not open codec [h264_nvenc]: Operation not permitted
[2023:06:11:12:46:44]: Error: Failed to derive device context: Unknown error occurred
```

### PR DESCRIPTION
**Pull request by cgutman**
## Description
This PR implements new protocol extensions for:
- Native touch and stylus input for Windows
- Additional controller buttons, such as Xbox Series X share button and DualShock/DualSense touchpad button
- Controller arrival metadata to allow the host to match the type of controller present on the client

It additionally stubs controller motion and touch events, which can be supported for the DS4 device but aren't implemented in this PR. Implementing these requires switching to sending raw DS4 input reports via ViGEmBus, which is a significant change that warrants its own PR.

Before I take this PR out of draft, I'm going to take a stab at implementing all this for Linux. Since we're not limited by ViGEmBus, we can emulate the full set of available controller features, like an Xbox Series X Elite controller with paddles, a regular Xbox Series X controller for Share button support, Nintendo Switch Pro controller, and DualShock 4 controller. 

I also need to track down a performance issue I saw when sending frequent stylus events. We might need to move input to a separate thread to avoid stalling the control thread processing the the ENet messages.

### Issues Fixed or Closed
Fixes #1362

## Type of Change
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Dependency update (updates to dependencies)
- [x] Documentation update (changes to documentation)
- [ ] Repository update (changes to repository files, e.g. `.github/...`)

## Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated the in code docstring/documentation-blocks for new or existing methods/components

## Branch Updates
LizardByte requires that branches be up-to-date before merging. This means that after any PR is merged, this branch
must be updated before it can be merged. You must also
[Allow edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [x] I want maintainers to keep my branch updated

### CODE REVIEW

**Comment by LegacyGamerHD** [comment]
touch is screen still kinda bugy i cant swipe and walk at same time in minecraft bedrock and it says it suports 10 fingers do again i compiled the moonlight android branch on my own so idk if it my issue or its a bug

**Comment by LegacyGamerHD** [comment]
also long pressing aka right click  doesnt hold it down it repeats

**Comment by cgutman** [comment]
All gamepad-related commits from this PR have been merged in #1401, #1402, and #1435.

Pen and touch support is now in #1483

Closing this PR as superseded.

**Comment by XPRAMT** [comment]
Using a stylus pen may experience intermittent lag (approximately every 10 to 20 seconds).

**Pull request closed without merging**
