### PR TITLE
Extend session timeout

### PR DESCRIPTION
**Pull request by zoeyjodon**
## Description
Use the ping timeout for the launch event's timeout value, to allow users of slower clients more time to connect.

## Type of Change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Dependency update (updates to dependencies)
- [ ] Documentation update (changes to documentation)
- [ ] Repository update (changes to repository files, e.g. `.github/...`)

## Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated the in code docstring/documentation-blocks for new or existing methods/components

## Branch Updates
LizardByte requires that branches be up-to-date before merging. This means that after any PR is merged, this branch
must be updated before it can be merged. You must also
[Allow edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [x] I want maintainers to keep my branch updated

### CODE REVIEW

**Comment by ReenigneArcher** [comment]
Thank you for the PR! We can consider this once you sign the CLA. If you have any questions please let me know.

**Review by ReenigneArcher — COMMENTED** [review]
This is not a requirement, but in our effort to improve our code documentation, would you mind adding documentation blocks for the two modified functions? https://docs.lizardbyte.dev/projects/sunshine/en/latest/source/src.html#src

**Comment by cgutman** [comment]
Which clients were needing an extended timeout?

**Comment by zoeyjodon** [comment]
> Which clients were needing an extended timeout?

I'm currently working on porting Moonlight to the 3DS. Setup and streaming are currently working alright with gamestream, so I'm trying to make sure it works with Sunshine too.

**Comment by zoeyjodon** [comment]
> This is not a requirement, but in our effort to improve our code documentation, would you mind adding documentation blocks for the two modified functions? https://docs.lizardbyte.dev/projects/sunshine/en/latest/source/src.html#src

Done! I'm always happy to help document

**Review by cgutman — APPROVED** [review]
Nope, LGTM.

**Pull request merged**
