### PR TITLE
Add winget releaser action

### PR DESCRIPTION
**Pull request by sitiom**
## Description

Continuation of #203 since it cannot be reopened.

[This action](https://bittu.eu.org/docs/wr-intro) automatically generates manifests for WinGet Community Repository ([microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs)) and submits them.

Before merging this:
1. ~Add a PAT with `public_repo` scope as a repository secret named `WINGET_TOKEN` (or rename the secret name in the workflow).~ @LizardByte-bot's PAT is used in the workflow.
2. Fork https://github.com/microsoft/winget-pkgs under @LizardByte
3. Make sure the PAT owner has signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs) for winget-pkgs.

If you would like to read about this action further, the documentation is [here](https://bittu.eu.org/docs/wr-intro), and the source code is [here](https://github.com/vedantmgoyal2009/winget-releaser).

If you want to see an example of a PR created using this action, see [microsoft/winget-pkgs/pulls (Pull request has been automatically created using 🛫 WinGet Releaser)](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+sort%3Aupdated-desc+Pull+request+has+been+automatically+created+using+%F0%9F%9B%AB+WinGet+Releaser).

### Notes

You would **need** to change the [`Publisher`](https://github.com/microsoft/winget-pkgs/blob/a011d13c4d75c07513fb8a0f6429f1efc7e98bb2/manifests/l/LizardByte/Sunshine/0.14.0/LizardByte.Sunshine.locale.en-US.yaml#L7) entry of the manifest to `LizardByte` on the next release (to match with the vendor info). You can add the change alongside the PR that Winget will automatically create in the next release.

### Issues Fixed or Closed

- Resolves https://github.com/SunshineStream/Sunshine/discussions/201
- Resolves https://github.com/vedantmgoyal2009/vedantmgoyal2009/issues/566

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated the docstring/documentation-blocks for new or existing methods/components

### CODE REVIEW

**Comment by sitiom** [comment]
Updated identifier to `LizardByte.Sunshine`. I have also made a PR to rename it in winget-pkgs (https://github.com/microsoft/winget-pkgs/pull/68000, https://github.com/microsoft/winget-pkgs/pull/68001).

**Comment by sitiom** [comment]
Note: You **need** to change the [`Publisher`](https://github.com/microsoft/winget-pkgs/blob/2110de8e4efc88f75c25b0da2a188857708c366e/manifests/s/SunshineStream/Sunshine/0.14.0/SunshineStream.Sunshine.locale.en-US.yaml#L7) entry to LizardByte on the next release (to match with the vendor info). You can add the change alongside the PR that Winget will automatically create in the next release.

**Comment by sitiom** [comment]
Separated the action to a separate workflow, as it currently only works with release events (https://github.com/vedantmgoyal2009/winget-releaser/issues/3). I have also put `GH_BOT_TOKEN` as the token to use. @ReenigneArcher you wouldn't mind that, right?

**Review by ReenigneArcher — APPROVED** [review]
- [x] repo forked
- [x] CLA signed by bot account

**Comment by sitiom** [comment]
@ReenigneArcher There is an extra step: You should keep the fork regularly updated with [Pull](https://github.com/apps/pull). See https://github.com/vedantmgoyal2009/winget-releaser/issues/32

**Pull request merged**
