### PR TITLE
Optionally allow the system installation of nlohmann_json to be used

### PR DESCRIPTION
**Pull request by chewi**
## Description
As before, this makes the Gentoo Linux package a little simpler. I did say that last time was my final unbundling request, but you've added this dependency since.

## Type of Change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Dependency update (updates to dependencies)
- [ ] Documentation update (changes to documentation)
- [ ] Repository update (changes to repository files, e.g. `.github/...`)

## Checklist
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have added or updated the in code docstring/documentation-blocks for new or existing methods/components

## Branch Updates
LizardByte requires that branches be up-to-date before merging. This means that after any PR is merged, this branch
must be updated before it can be merged. You must also
[Allow edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [X] I want maintainers to keep my branch updated

### CODE REVIEW

**Comment by ReenigneArcher** [comment]
Can we install it as a package in all of our build pipelines? That would be preferred to using a submodule anyway.

**Comment by chewi** [comment]
I was going to say no, as I didn't expect other distributions to bother, given that it's just a bunch of headers, but turns out they all have it!

* Arch - nlohmann-json
* Fedora - nlohmann-json-devel
* Debian/Ubuntu - nlohmann-json3-dev

**Comment by ReenigneArcher** [comment]
It's also available for Windows and macOS.

https://packages.msys2.org/base/mingw-w64-nlohmann-json
https://formulae.brew.sh/formula/nlohmann-json#default

Would you mind making a PR to use the installed package instead? It would require updates to our CI/Docker files, and docs. Otherwise, I can put it on my list of things to do.

**Comment by chewi** [comment]
I'm on it.

**Comment by chewi** [comment]
Closing in favour of #2161.

**Pull request closed without merging**
