### PR TITLE
fix(linux): Arch requires library at runtime

### PR DESCRIPTION
**Pull request by pyamsoft**
## Description
On my Archlinux system, the package builds correctly, but without including the libappindicator-gtk3 dependency, it fails to launch at runtime with the following error message:

```/usr/bin/sunshine: error while loading shared libraries: libappindicator3.so.1: cannot open shared object file: No such file or directory```

This patch adds the required library as a dependency for runtime.

## Type of Change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Dependency update (updates to dependencies)
- [ ] Documentation update (changes to documentation)
- [ ] Repository update (changes to repository files, e.g. `.github/...`)

## Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated the in code docstring/documentation-blocks for new or existing methods/components

## Branch Updates
LizardByte requires that branches be up-to-date before merging. This means that after any PR is merged, this branch
must be updated before it can be merged. You must also
[Allow edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [ ] I want maintainers to keep my branch updated

### CODE REVIEW

**Review by psyke83 — APPROVED** [review]
This library is probably installed Arch users' systems if using GNOME and Network Manager, so it's probably an oversight.

From v0.23.0 release binary:
```
$ ldd /usr/bin/sunshine | grep app
        libayatana-appindicator3.so.1 => /usr/lib/libayatana-appindicator3.so.1 (0x000079cdb7c2e000)
$ sudo pacman -R libappindicator-gtk3
checking dependencies...
error: failed to prepare transaction (could not satisfy dependencies)
:: removing libappindicator-gtk3 breaks dependency 'libappindicator-gtk3' required by network-manager-applet
```

**Comment by pyamsoft** [comment]
Hi, thanks for the approval!

As a fun aside:
Ironically, I am an Arch Gnome user. The appindicator library is not installed as a requirement unless you have network-manager-applet, which is only a required dep of gnome-flashback session. The reason I encountered this in the first place was because I do not have the gnome flashback package installed on my machine (or any other of the various packages that would otherwise require it)

**Comment by ReenigneArcher** [comment]
@psyke83 Sunshine can use either appindicator version, 'libayatana-appindicator' or 'libappindicator-gtk3'...

I guess what happened is they may have had the gtk3 version installed when installing sunshine.

https://github.com/LizardByte/Sunshine/blob/7e26d2fd3064c6adf3e7a52a275046dd0cf194be/cmake/compile_definitions/linux.cmake#L202-L210

I'm thinking we should just reverse the order when checking for this. Ayatana version should be primary.

**Comment by pyamsoft** [comment]
Sounds like this PR should be closed in favor of updating the cmake file then?

**Comment by psyke83** [comment]
> @psyke83 Sunshine can use either appindicator version, 'libayatana-appindicator' or 'libappindicator-gtk3'...
> 
> I guess what happened is they may have had the gtk3 version installed when installing sunshine.
> 
> https://github.com/LizardByte/Sunshine/blob/7e26d2fd3064c6adf3e7a52a275046dd0cf194be/cmake/compile_definitions/linux.cmake#L202-L210
> 
> I'm thinking we should just reverse the order when checking for this. Ayatana version should be primary.

I think so? The PKGBUILD will install the ayatana library first, so it can't really conflict if the legacy library is also installed. I supposed we could also remove the ayatana library from the PKGBUILD and instead inject the library selected via cmake via an environment variable instead, but that might be too much hassle.

**Comment by ReenigneArcher** [comment]
> Sounds like this PR should be closed in favor of updating the cmake file then?

Yes

**Comment by pyamsoft** [comment]
I will close unless you would like to continue discussion here - or please close from your end when done. Thanks!

**Pull request closed without merging**
