### PR TITLE
docs: add note on how to find Epic Games URI

### PR DESCRIPTION
**Pull request by seadowg**
## Description

A small note here would have helped me a lot when working out how to deal with games that require Epic's launcher, so I thought I'd add one in.

## Type of Change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Dependency update (updates to dependencies)
- [x] Documentation update (changes to documentation)
- [ ] Repository update (changes to repository files, e.g. `.github/...`)

## Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added or updated the in code docstring/documentation-blocks for new or existing methods/components

### CODE REVIEW

**Review by ReenigneArcher — CHANGES_REQUESTED** [review]
We should probably use more specific instructions.

> To find the Epic Games app ID, go to C: \ Program Files \ Epic Games \ "Name of the Game" \.egstore. Then open the MANCPN file in notepad. The game ID will be in the “AppName” field.

https://enestech.zendesk.com/hc/en-gb/articles/360010884420-Where-to-find-Steam-Origin-Battle-net-Riot-Games-Epic-Games-app-ID

the Surviving Mars example of that file is
```json
{
	"FormatVersion": 0,
	"CatalogNamespace": "d759128018124dcabb1fbee9bb28e178",
	"CatalogItemId": "20729b9176c241f0b617c5723e70ec2d",
	"AppName": "Ovenbird"
}
```

Both the CatalogNamespace and CatalogItemId are required to generate the URI.

**Comment by ReenigneArcher** [comment]
@seadowg I'll convert this to draft until you respond.

**Comment by seadowg** [comment]
@ReenigneArcher sorry I haven't had a chance to get back to this! Should be able to have another look this week.

**Comment by seadowg** [comment]
> We should probably use more specific instructions.
> 
> > To find the Epic Games app ID, go to C: \ Program Files \ Epic Games \ "Name of the Game" .egstore. Then open the MANCPN file in notepad. The game ID will be in the “AppName” field.
> 
> https://enestech.zendesk.com/hc/en-gb/articles/360010884420-Where-to-find-Steam-Origin-Battle-net-Riot-Games-Epic-Games-app-ID
> 
> the Surviving Mars example of that file is
> 
> ```json
> {
> 	"FormatVersion": 0,
> 	"CatalogNamespace": "d759128018124dcabb1fbee9bb28e178",
> 	"CatalogItemId": "20729b9176c241f0b617c5723e70ec2d",
> 	"AppName": "Ovenbird"
> }
> ```
> 
> Both the CatalogNamespace and CatalogItemId are required to generate the URI.

I was able to just copy the URI and use as-is from Epic's created desktop shortcut. Would that not work for all games? It seems less involved to me than constructing the URI from its parts.

**Comment by ReenigneArcher** [comment]
Yea, but I don't know how that process would be on other platforms, like macOS.

It's also kind of obvious. If you want to replicate how a shortcut works, it's pretty clear to make the shortcut and inspect it.

**Comment by ReenigneArcher** [comment]
Sorry, but I'll be closing this PR. I think it's kind of an obvious answer to any game/app whether from Epic, Steam, or anywhere else.

In place of this note, I've added an automatic game scanner feature (at least for Epic and Steam) to our roadmap.

**Comment by seadowg** [comment]
No worries! Sorry I didn't get a chance to reply before now.

**Pull request closed without merging**
