### PR TITLE
Remove unnecessary tray_update() calls

### LINKED ISSUE #2065: Taskbar icon sometimes unresponsive
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

Sometimes right-clicking on the Sunshine taskbar icon does nothing

### Expected Behavior

The taskbar context menu should show up

### Additional Context

_No response_

### Host Operating System

Windows

### Operating System Version

11 23H2 (OS Build 22631.3007)

### Architecture

64 bit

### Sunshine commit or version

0.21.0

### Package

Windows - Winget (Third Party)

### GPU Type

Nvidia

### GPU Model

RTX 3070  Ti

### GPU Driver/Mesa Version

546.33

### Capture Method (Linux Only)

_No response_

### Config

```Shell
origin_web_ui_allowed = pc
```

### Apps

_No response_

### Relevant log output

```shell
N/A
```

### PR DESCRIPTION
**Pull request by ns6089**
## Description

Remove unnecessary tray_update() calls.
They're unsafe on Windows outside of UI thread.

### Issues Fixed or Closed

- Fixes #2065

## Type of Change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Dependency update (updates to dependencies)
- [ ] Documentation update (changes to documentation)
- [ ] Repository update (changes to repository files, e.g. `.github/...`)

## Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added or updated the in code docstring/documentation-blocks for new or existing methods/components

### CODE REVIEW

**Comment by ns6089** [comment]
And it still doesn't fix the issue...

**Comment by ns6089** [comment]
Moving `tray_update()` into UI thread and calling it synchronously through `SendMessage()` resolves the freeze.
It is a threading issue after all.

**Comment by ReenigneArcher** [comment]
> Moving `tray_update()` into UI thread and calling it synchronously through `SendMessage()` resolves the freeze. It is a threading issue after all.

Could this same update give us tray icon support on macOS?

**Comment by ns6089** [comment]
> Could this same update give us tray icon support on macOS?

I have absolutely no idea what's needed to be done there.

**Comment by ns6089** [comment]
It's far more easier and failure-proof to rewrite Windows tray logic in cpp from the ground up than trying to fix the thing the library has turned into.
Closing this for now, maybe someone else will take over.
Or I get sufficiently annoyed but the non-functional tray.

**Pull request closed without merging**
