### PR TITLE
feat!: drop advertised resolutions and fps

### PR DESCRIPTION
**Pull request by ReenigneArcher**
## Description

Drop support for advertised resolutions and fps. Any clients still using this?

Moonlight maintainers, please verify this doesn't break any of your clients.

- [x] @cgutman (Official)
- [x] @TheElixZammuto (UWP/Xbox)
- [x] @XITRIX (Switch)
- [ ] @GaryOderNichts (Wii U)
- [x] @mariotaku (LG webOS)
- [ ] @xyzz (Vita)
- [ ] @KyroFrCode (Tizen fork 1)
- [ ] @OneLiberty (Tizen fork 2)

## Type of Change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Dependency update (updates to dependencies)
- [ ] Documentation update (changes to documentation)
- [ ] Repository update (changes to repository files, e.g. `.github/...`)

## Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated the in code docstring/documentation-blocks for new or existing methods/components

## Branch Updates
LizardByte requires that branches be up-to-date before merging. This means that after any PR is merged, this branch
must be updated before it can be merged. You must also
[Allow edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [ ] I want maintainers to keep my branch updated

### CODE REVIEW

**Comment by mariotaku** [comment]
I tried to ignore display modes and didn't see any problem.

**Comment by XITRIX** [comment]
Switch client still rely on it, will try to add required changes in near future

**Comment by GaryOderNichts** [comment]
Wii U uses @mariotaku's modified libgamestream, which still parses the supported modes. I'm not sure if this will fail, if the server doesn't respond with them. I'll have to test this later.

**Comment by XITRIX** [comment]
Do I understand correctly, that I could just remove all this checks?
image
Also what about `server->unsupported` and `!server->supports4K` I'm not 100% sure what "unsupported" means in this context and could I ignore it, and should I leave 4K check as it is or remove it as well?

I will leave it like this for now and will change after any feedback from your side, thanks!
image

**Comment by TheElixZammuto** [comment]
Moonlight UWP does work as expected with this version of Sunshine. My libgamestream is derived from the moonlight-embedded one btw, but the app never checked the supported resolutions.

**Comment by XITRIX** [comment]
I've made all necessary modifications, next Moonlight-Switch release should works fine without screen modes list

**Pull request merged**
