### PR TITLE
build(docs): make Readme more homogenous

### PR DESCRIPTION
**Pull request by gogo2464**
## Description

Fixes and issue in the documentation following a pretty documentation template. The documentation is now clean.

## Type of Change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Dependency update (updates to dependencies)
- [X] Documentation update (changes to documentation)
- [ ] Repository update (changes to repository files, e.g. `.github/...`)

## Checklist
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated the in code docstring/documentation-blocks for new or existing methods/components

for testing

### CODE REVIEW

**Comment by ReenigneArcher** [comment]
Since this text only appears when the badge image cannot be loaded, and this change is very insignificant, I'm going to close this.

**Comment by ReenigneArcher** [comment]
Also, since I believe you are trying to gain access to attack the repo you'll be blocked.

**Comment by gogo2464** [comment]
It was for bug bounty

**Comment by ReenigneArcher** [comment]
This is clearly a code injection attempt. 
image

**Pull request closed without merging**
