### PR TITLE
build(cmake): copy asset files to build dir

### PR DESCRIPTION
**Pull request by ReenigneArcher**
## Description

This PR makes a change to the build process, where asset files are copied to the build directory, so that the generated binary can be run without an install. This is mostly to improve the development process, although some users have wanted to run Sunshine without an install in the past as well.

This uses the `file(COPY ...)` method which actually copies the files when running cmake, before the build.

## Type of Change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Dependency update (updates to dependencies)
- [ ] Documentation update (changes to documentation)
- [ ] Repository update (changes to repository files, e.g. `.github/...`)

## Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated the in code docstring/documentation-blocks for new or existing methods/components

## Branch Updates
LizardByte requires that branches be up-to-date before merging. This means that after any PR is merged, this branch
must be updated before it can be merged. You must also
[Allow edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [ ] I want maintainers to keep my branch updated

### CODE REVIEW

**Comment by ReenigneArcher** [comment]
@FrogTheFrog I think you asked about this before, if you want to give it a try.

**Comment by FrogTheFrog** [comment]
> @FrogTheFrog I think you asked about this before, if you want to give it a try.

No, it was about:
https://github.com/LizardByte/Sunshine/blob/1329c510b15ef715c136ab964ece1bfd26b914cb/cmake/targets/common.cmake#L55

**Comment by FrogTheFrog** [comment]
I don't have bash on Windows...

**Comment by ReenigneArcher** [comment]
> > @FrogTheFrog I think you asked about this before, if you want to give it a try.
> 
> No, it was about:
> 
> https://github.com/LizardByte/Sunshine/blob/1329c510b15ef715c136ab964ece1bfd26b914cb/cmake/targets/common.cmake#L55

Okay, that is actually another issue I'm facing. While I do have bash, for some reason on CLion it finds very old versions of npm and node, but I can't reproduce it in any of my shells manually.

**Pull request merged**
