### PR TITLE
fix(ui): web ui now always loads default locale on errors

### PR DESCRIPTION
**Pull request by PVermeer**
## Description
[Bazzite](https://bazzite.gg/) has some issues with sunshine where at the time of writing the web ui will not load.
`/api/configLocale` Returns an xml error report.

Bazzite uses a custom build from https://copr.fedorainfracloud.org/coprs/matte-schwartz/sunshine .

**I could not reproduce the error on base Fedora 39 with the current nightly build.**

The fix includes a `catch` so the default will always be loaded and the app will not crash and be more future-proof.
Also made it a bit more readable.

### Issues Fixed or Closed
No issue just PR

## Type of Change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Dependency update (updates to dependencies)
- [ ] Documentation update (changes to documentation)
- [ ] Repository update (changes to repository files, e.g. `.github/...`)

## Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated the in code docstring/documentation-blocks for new or existing methods/components

## Branch Updates
LizardByte requires that branches be up-to-date before merging. This means that after any PR is merged, this branch
must be updated before it can be merged. You must also
[Allow edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [x] I want maintainers to keep my branch updated

### CODE REVIEW

**Comment by ReenigneArcher** [comment]
There's almost no way this should fail, unless Sunshine isn't responding the API request...

**Comment by PVermeer** [comment]
I know, it's super weird, but it's happening on my system...
There is something going on in the fedora copr build and **not** with this repo.
Streaming works fine btw.

I tried a bunch of different builds and its not reproducible in any way. 

So it's just a little code improvement I spotted when tracking down the issue so this can't happen anyway in the future.

**Comment by ReenigneArcher** [comment]
I'm planning to work with Matte to bring the copr builds over to https://copr.fedorainfracloud.org/coprs/lizardbyte/Sunshine/

If it's something specific to those builds, we'll probably find it during that process.

**Comment by PVermeer** [comment]
Could also be bazzite related. I could not test on the bazzite image because of the read-only fs. Post scripts (setcap) cannot run.

**Comment by PVermeer** [comment]
FYI:
`sunshine 0.22.2-1.git.20240328.c53920a.fc39 -> 0.22.2-3.fc39`
fixed it.

**Comment by ReenigneArcher** [comment]
@PVermeer I'm not sure I understand your message. Those commits don't appear to be related to Sunshine. At least nothing recent in nightly.

**Comment by PVermeer** [comment]
Sorry for the confusion, I think the commit is from the copr repo of Matte. I don't know much about copr.

Since you're planning to work with him I thought you might wanted to know.

**Pull request closed without merging**
