### PR TITLE
ci: Add support for Fedora 39

### PR DESCRIPTION
**Pull request by EyeCantCU**
## Description
This change implements support for Fedora 39

## Type of Change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Dependency update (updates to dependencies)
- [ ] Documentation update (changes to documentation)
- [ ] Repository update (changes to repository files, e.g. `.github/...`)

## Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added or updated the in code docstring/documentation-blocks for new or existing methods/components

## Branch Updates
LizardByte requires that branches be up-to-date before merging. This means that after any PR is merged, this branch
must be updated before it can be merged. You must also
[Allow edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [x] I want maintainers to keep my branch updated

### CODE REVIEW

**Comment by ReenigneArcher** [comment]
I'll probably wait until Fedora 37 is EOL to not add extra ci burden.

**Comment by ArclightMat** [comment]
FYI: The build will fail since you're specifying "boost-devel-1.78.0\*", which is unavailable for Fedora 39.
A simple change to "boost-devel-1.81.0\*" will work (it did work on my local build). I'm not a professional packager myself, but I believe it would be better if we weren't hard-coding the version numbers for dependencies unless it is an actual necessity.

**Comment by ReenigneArcher** [comment]
I'm actually going to close this. I know that you are probably just trying to help out the project, and I appreciate that... but it's going to take me longer to review this than to just create the image myself.

**Comment by ReenigneArcher** [comment]
Replaced by #1827

**Pull request closed without merging**
