### PR TITLE
build(linux): honor install prefix for tray icon

### PR DESCRIPTION
**Pull request by istori1**
## Description
Use install prefix for the tray icon location.

## Type of Change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Dependency update (updates to dependencies)
- [ ] Documentation update (changes to documentation)
- [ ] Repository update (changes to repository files, e.g. `.github/...`)

## Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated the in code docstring/documentation-blocks for new or existing methods/components

## Branch Updates
LizardByte requires that branches be up-to-date before merging. This means that after any PR is merged, this branch
must be updated before it can be merged. You must also
[Allow edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [x] I want maintainers to keep my branch updated

### CODE REVIEW

**Comment by ReenigneArcher** [comment]
I don't think gtk will look in any specified location, that's why I forced it to `/usr`. Can you give me a use case where this needs to be somewhere besides `/usr`?

**Comment by hfiguiere** [comment]
> I don't think gtk will look in any specified location, that's why I forced it to `/usr`. Can you give me a use case where this needs to be somewhere besides `/usr`?

This is not true. It should be installed in the prefix. This is the standard.
With immutable systems like Fedora Silverblue, you can NOT write in `/usr`.

**Comment by ReenigneArcher** [comment]
Okay, but our flatpak prefix is `/app`. I have not verified but I'm doubting it will find icons in this location. Please correct me if it will find them there.

https://github.com/LizardByte/Sunshine/blob/d70d084f9fbb4e0150977a89d94937418a3ccf9c/packaging/linux/flatpak/dev.lizardbyte.sunshine.yml#L218

**Comment by hfiguiere** [comment]
Flatpak has nothing to do here. Installing icons have to follow the prefix. That's what prefix is for.

**Comment by hfiguiere** [comment]
BTW it is wrong to set pass ` -DCMAKE_INSTALL_PREFIX=/app ` in a flatpak manifest. This is why buildsystem `cmake` or `cmake-ninja` exist, as they manage this kind of things.

**Pull request merged**
