### PR TITLE
docs(advanced-usage): cross reference config UI

### PR DESCRIPTION
**Pull request by ReenigneArcher**
## Description

This PR adds hyperlinks in the docs to take the user to the location in the UI where the config categories/settings are located.

Todo:
- [x] Add hash watcher event to toggle config UI tab -> https://developer.mozilla.org/en-US/docs/Web/API/Window/hashchange_event ... see #2002 

## Type of Change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Dependency update (updates to dependencies)
- [x] Documentation update (changes to documentation)
- [ ] Repository update (changes to repository files, e.g. `.github/...`)

## Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated the in code docstring/documentation-blocks for new or existing methods/components

## Branch Updates
LizardByte requires that branches be up-to-date before merging. This means that after any PR is merged, this branch
must be updated before it can be merged. You must also
[Allow edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [ ] I want maintainers to keep my branch updated

### CODE REVIEW

**Comment by ReenigneArcher** [comment]
merge after #2002

**Comment by cgutman** [comment]
I like the idea but what about people that are using non-default ports?

**Comment by ReenigneArcher** [comment]
> I like the idea but what about people that are using non-default ports?

I'm not sure how to handle that really. It also won't work if someone is viewing the docs from a machine other than the one running sunshine.

**Comment by ReenigneArcher** [comment]
> Maybe, there could be possibly be a field at the top where they can enter the base url, and then a javascript method could overwrite all the urls.

I'll work on this in a follow up PR.

**Pull request merged**
