### PR TITLE
change org to LizardByte

### PR DESCRIPTION
**Pull request by ReenigneArcher**
## Description

It is becoming increasingly burdensome to maintain multiple GitHub organizations. Therefore Sunshine will move to LizardByte (formerly RetroArcher).
- updates references from `SunshineStream` to `LizardByte`
- updates issue template
- updates docker readme

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated the docstring/documentation-blocks for new or existing methods/components

### CODE REVIEW

**Comment by ReenigneArcher** [comment]
Todo:
- [ ] complete/publish new website
  - [ ] including new discord page
- [ ] fix readthedocs integration
- [ ] fix crowdin integration
- [ ] move to LizardByte

**Review by TheElixZammuto — COMMENTED** [review]
I have a couple questions regarding this decision:

1) Are you planning to change the project name other than the Organization Name?

2) What is the legal status of LizardByte, is this is a company (or are you planning to make one?) or an open source organizazion like Sunshine is right now?

3) How are you planning to make clear that while LizardByte and Sunshine are both maintened by you, these are two different and indipendent projects? 

4) Is the governance going to change when changing between repositories? At the moment there are no public member inside the org. 

5) What are your plans with the actual SunshineStream org?

I personally trust you and thank you for all the work you've done here, but also I want to make sure Sunshine wouldn't suffer again the same problems it had before, especially since that between the OpenStream project, Maxximizer, and the organizazion change we already have got a very turbulent project history.

**Comment by TheElixZammuto** [comment]
Also tagging for FYI @cgutman @loki-47-6F-64

**Comment by ReenigneArcher** [comment]
> I have a couple questions regarding this decision:
> 
> 1) Are you planning to change the project name other than the Organization Name?

Only the org name is changing. My other project name will not become LizardByte.

> 2) What is the legal status of LizardByte, is this is a company (or are you planning to make one?) or an open source organizazion like Sunshine is right now?

It is not a legal company currently. I may make it one in the future, but honestly I am not sure if I will or not.

> 3) How are you planning to make clear that while LizardByte and Sunshine are both maintened by you, these are two different and indipendent projects? 

I believe the different repo/project names should suffice. The website will also showcase the org projects. I hope to get this published soon, mostly waiting on the new logo.

> 4) Is the governance going to change when changing between repositories? At the moment there are no public member inside the org. 

Before I add any members to the new org, I need to ensure all the development guidelines are clearly defined so that common practices among the different repos are understood.

> 5) What are your plans with the actual SunshineStream org?

It will continue to exist but remain unused. I will update the .github profile to notify users of the change. GitHub will redirect most links to the new org automatically.

> I personally trust you and thank you for all the work you've done here, but also I want to make sure Sunshine wouldn't suffer again the same problems it had before, especially since that between the OpenStream project, Maxximizer, and the organizazion change we already have got a very turbulent project history.

Thank you, and I understand. It was a difficult decision to do this (and even more so for RetroArcher) but in the end I believe the development process will be much more efficient. There's also an opportunity to share many repos, and resources among the projects. For example both Sunshine and RetroArcher will use the `db` repo. Sunshine will use it for the game cover pr.

**Comment by TheElixZammuto** [comment]
Gotcha, thank you for your insight. LGTM!

**Comment by shodanx2** [comment]
As part of this project re-hosting, please update the search engine optimizations, so your user can find this project.

Right now go to google search for 
"sunshine streaming" or "moonlight server" or "nvidia gamestream open source server" 

And you will likely end up on the abandonned repository https://github.com/loki-47-6F-64/sunshine

There's no mention on that repo's readme but if you go in it's [discussion section](https://github.com/loki-47-6F-64/sunshine/discussions/325) you'll find the actual repo is 

https://github.com/SunshineStream/Sunshine

which now redirects to 

https://github.com/LizardByte/Sunshine

Why doesn't moonlight's impressively proffessional looking [website](https://moonlight-stream.org/) have any mention of this experimental server ? 

Don't they think it's good enough ?  I mean, I tried it, and it's just awesome. I tried it on a laptop that has intel graphics and it runs just amazing !

The few users who do manage to find this project will be very happy, even if they cut themselves on the few remaining sharp edges, this project is production ready, like , right now, it deserves better advertising !

**Comment by ReenigneArcher** [comment]
@shodanx2 we have no control over Loki's repo, nor over how searching github projects is handled. Loki's repo has more stars so it will appear first.

You want this one to appear first, give us a star. The SunshineStream org is abandoned as it was too difficult to maintain multiple github orgs, multiple discord servers, multiple websites, etc; however I kept control over the org name in order to ensure the github redirect continues to work.

**Pull request merged**
