### PR TITLE
Revert "Remove useless texture size queries for every frame in displa…

### PR DESCRIPTION
**Pull request by kelvie**
…y_ram_t"

This reverts commit ebe01ce20b06c6f10392f945c1c7083ed3aa733f.

Looks like this commit undos the fixes in #649 and #884. Might be wise to add a comment so it doesn't get removed again (since it doesn't look like it does anything)

## Description
Revert a change. It may be wise to add a comment here so it isn't removed again in the future.

## Type of Change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Dependency update (updates to dependencies)
- [ ] Documentation update (changes to documentation)
- [ ] Repository update (changes to repository files, e.g. `.github/...`)

## Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added or updated the in code docstring/documentation-blocks for new or existing methods/components

## Branch Updates
LizardByte requires that branches be up-to-date before merging. This means that after any PR is merged, this branch
must be updated before it can be merged. You must also
[Allow edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [x] I want maintainers to keep my branch updated

### CODE REVIEW

**Comment by kelvie** [comment]
@cgutman @ReenigneArcher who made the change and merged the original change

**Comment by cgutman** [comment]
> It may be wise to add a comment here so it isn't removed again in the future.

I agree. Please add comments on those linking them back to the original GitHub issues so they don't get removed again.

**Comment by kelvie** [comment]
> > It may be wise to add a comment here so it isn't removed again in the future.
> 
> I agree. Please add comments on those linking them back to the original GitHub issues so they don't get removed again.

Did y'all want me to put this in a separate commit or to amend the revert commit?

**Comment by ReenigneArcher** [comment]
Amending is fine

**Comment by kelvie** [comment]
It is amended.

**Pull request merged**
