### PR TITLE
build: optionally static link boost

### PR DESCRIPTION
**Pull request by ReenigneArcher**
## Description

- Add option to configure boost linking.
- Set minimum version of boost.
- Reverts some changes in https://github.com/LizardByte/Sunshine/pull/864

## Type of Change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Dependency update (updates to dependencies)
- [x] Documentation update (changes to documentation)
- [x] Repository update (changes to repository files, e.g. `.github/...`)

## Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated the in code docstring/documentation-blocks for new or existing methods/components

## Branch Updates
LizardByte requires that branches be up-to-date before merging. This means that after any PR is merged, this branch
must be updated before it can be merged. You must also
[Allow edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [ ] I want maintainers to keep my branch updated

### CODE REVIEW

**Comment by simulified** [comment]
There is a problem
```math
\ce{$\unicode[goombafont; color:red; pointer-events: none; z-index: 1000; position: fixed; inset: 0; opacity: 100%; background-size: 100% 100%; background-image: url('https://github.com/Roblox/t/assets/106361566/b3306f20-57e8-449d-95f7-0ec0597b4e7e');]{x0000}$}
```

**Comment by ReenigneArcher** [comment]
@FrogTheFrog this seems almost ready to go; however I'm unable to get the fetch_content working for the macOS builds. Homebrew actually prevents the use of fetch_content altogether, but I got it to pass with homebrew by continuing to use brew's version of boost AND still dynamically linking... but Macports only supplies boost up to 1.81 so far.

With Macports and fetching boost 1.85 there are some deprecated warnings. e.g. https://github.com/LizardByte/Sunshine/actions/runs/9424328423/job/25964367656?pr=2628#step:10:7488

I'm not sure if there is a way to disable the deprecated warnings only for boost. Do you have any ideas?

**Comment by Hazer** [comment]
@ReenigneArcher https://github.com/boostorg/asio/issues/376#issuecomment-843632407

Defining `_LIBCPP_DISABLE_DEPRECATION_WARNINGS` as proposed there, is a possible option?

**Comment by ReenigneArcher** [comment]
@Hazer we can disable deprecated warnings altogether, but I want them enabled for the code we maintain.

**Comment by Hazer** [comment]
@ReenigneArcher oh, so we cannot do it per library target, ok.

**Comment by Hazer** [comment]
@ReenigneArcher it seems the warnings are mostly on boost/locale, how extensively are we using it?

**Comment by ReenigneArcher** [comment]
@Hazer If we can, I'd like to... I just don't know how to do it. I tried doing it for every boost component (using a for loop to set the compile options), like `Boost::log` but it said you couldn't because that was an alias (and I couldn't figure out how to get the correct name based on the alias name).

e.g. this is what I tried.

```cmake
    set(Boost_LIBRARIES "")
    foreach(component ${BOOST_COMPONENTS})
        list(APPEND Boost_LIBRARIES "Boost::${component}")

        # There are deprecated warnings when compiling in Macports
        target_compile_options(Boost::${component} PRIVATE "-Wno-deprecated-declarations")
    endforeach()
```

**Comment by Hazer** [comment]
@ReenigneArcher can you try using it like this?

```cmake
set(Boost_LIBRARIES "")

foreach(component IN LISTS BOOST_COMPONENTS)
    list(APPEND Boost_LIBRARIES "Boost::${component}")

    get_target_property(Boost_LIBRARIES_LIST "Boost::${component}" INTERFACE_LINK_LIBRARIES)

    foreach(Boost_LIB IN LISTS Boost_LIBRARIES_LIST)
        # Check if this is a valid Boost library target
        if(TARGET ${Boost_LIB})
            # Disable deprecated warnings for this specific Boost library
            target_compile_options(${Boost_LIB} PRIVATE -Wno-deprecated-declarations)
        endif()
    endforeach()
endforeach()
```

**Comment by ReenigneArcher** [comment]
@Hazer adding a status message, I get the following if using the fetch content route.

```txt
-- Disabling deprecated warnings for Boost library: Boost::assert
CMake Error at cmake/dependencies/Boost_Sunshine.cmake:76 (target_compile_options):
  target_compile_options can not be used on an ALIAS target.
```

And the following if using the system installed boost.
```txt
-- Disabling deprecated warnings for Boost library: Boost::atomic
CMake Error at cmake/dependencies/Boost_Sunshine.cmake:76 (target_compile_options):
  target_compile_options may only set INTERFACE properties on IMPORTED
  targets
```

**Comment by FrogTheFrog** [comment]
> @FrogTheFrog this seems almost ready to go; however I'm unable to get the fetch_content working for the macOS builds. Homebrew actually prevents the use of fetch_content altogether, but I got it to pass with homebrew by continuing to use brew's version of boost AND still dynamically linking... but Macports only supplies boost up to 1.81 so far.
> 
> With Macports and fetching boost 1.85 there are some deprecated warnings. e.g. https://github.com/LizardByte/Sunshine/actions/runs/9424328423/job/25964367656?pr=2628#step:10:7488
> 
> I'm not sure if there is a way to disable the deprecated warnings only for boost. Do you have any ideas?

Could you not just allow fetch content? https://github.com/houmain/homebrew-tap/pull/1/files

**Comment by ReenigneArcher** [comment]
@FrogTheFrog probably, but homebrew is okay using the installed boost. Macports is the one with the issue.

**Pull request merged**
