### PR TITLE
fix curl static link

### PR DESCRIPTION
**Pull request by ReenigneArcher**
## Description

- fixes curl issue building locally (on Windows)

## Type of Change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Dependency update (updates to dependencies)
- [ ] Documentation update (changes to documentation)
- [ ] Repository update (changes to repository files, e.g. `.github/...`)

## Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated the in code docstring/documentation-blocks for new or existing methods/components

## Branch Updates
LizardByte requires that branches be up-to-date before merging. This means that after any PR is merged, this branch
must be updated before it can be merged. You must also
[Allow edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [x] I want maintainers to keep my branch updated

### CODE REVIEW

**Comment by ReenigneArcher** [comment]
@psyke83 please let me know if you see anything potentially wrong with this change

**Comment by psyke83** [comment]
That preprocessor flag is already set here: https://github.com/LizardByte/Sunshine/blob/master/CMakeLists.txt#L79

```
# grep -r CURL_STATICLIB CMakeCache.txt
CURL_STATIC_CFLAGS:INTERNAL=-DCURL_STATICLIB
CURL_STATIC_CFLAGS_OTHER:INTERNAL=-DCURL_STATICLIB
```

If your build failed to statically link curl, it may mean that  you're missing pkg-config (`pkg-config` on Ubuntu, `mingw-w64-x86_64-pkgconf` on mingw).

**Comment by ReenigneArcher** [comment]
> That preprocessor flag is already set here: https://github.com/LizardByte/Sunshine/blob/master/CMakeLists.txt#L79
> 
> ```
> # grep -r CURL_STATICLIB CMakeCache.txt
> CURL_STATIC_CFLAGS:INTERNAL=-DCURL_STATICLIB
> CURL_STATIC_CFLAGS_OTHER:INTERNAL=-DCURL_STATICLIB
> ```
> 
> If your build failed to statically link curl, it may mean that you're missing pkg-config (`pkg-config` on Ubuntu, `mingw-w64-x86_64-pkgconf` on mingw).
> 
> If you can verify that's the problem, perhaps you could repurpose this PR to add those packages to the build dependency instructions.

I have the mingw package installed and get this error (without the change in this PR)

```txt
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles\sunshine.dir/objects.a(httpcommon.cpp.obj):httpcommon.cpp:(.text+0xedf): undefined reference to `__imp_curl_easy_init'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles\sunshine.dir/objects.a(httpcommon.cpp.obj):httpcommon.cpp:(.text+0xef2): undefined reference to `__imp_curl_easy_escape'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles\sunshine.dir/objects.a(httpcommon.cpp.obj):httpcommon.cpp:(.text+0xf09): undefined reference to `__imp_curl_free'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles\sunshine.dir/objects.a(httpcommon.cpp.obj):httpcommon.cpp:(.text+0xf12): undefined reference to `__imp_curl_easy_cleanup'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles\sunshine.dir/objects.a(httpcommon.cpp.obj):httpcommon.cpp:(.text+0xf5f): undefined reference to `__imp_curl_url'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles\sunshine.dir/objects.a(httpcommon.cpp.obj):httpcommon.cpp:(.text+0xf74): undefined reference to `__imp_curl_url_set'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles\sunshine.dir/objects.a(httpcommon.cpp.obj):httpcommon.cpp:(.text+0xf8a): undefined reference to `__imp_curl_url_get'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles\sunshine.dir/objects.a(httpcommon.cpp.obj):httpcommon.cpp:(.text+0xf97): undefined reference to `__imp_curl_url_cleanup'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles\sunshine.dir/objects.a(httpcommon.cpp.obj):httpcommon.cpp:(.text+0xfce): undefined reference to `__imp_curl_free'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles\sunshine.dir/objects.a(httpcommon.cpp.obj):httpcommon.cpp:(.text+0xfd7): undefined reference to `__imp_curl_url_cleanup'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles\sunshine.dir/objects.a(httpcommon.cpp.obj):httpcommon.cpp:(.text+0x29d8): undefined reference to `__imp_curl_easy_init'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles\sunshine.dir/objects.a(httpcommon.cpp.obj):httpcommon.cpp:(.text+0x2a08): undefined reference to `__imp_curl_easy_setopt'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles\sunshine.dir/objects.a(httpcommon.cpp.obj):httpcommon.cpp:(.text+0x2a4f): undefined reference to `__imp_curl_easy_perform'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles\sunshine.dir/objects.a(httpcommon.cpp.obj):httpcommon.cpp:(.text+0x2a73): undefined reference to `__imp_curl_easy_cleanup'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles\sunshine.dir/objects.a(httpcommon.cpp.obj):httpcommon.cpp:(.text+0x2abc): undefined reference to `__imp_curl_easy_cleanup'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles\sunshine.dir/objects.a(httpcommon.cpp.obj):httpcommon.cpp:(.text+0x2d2d): undefined reference to `__imp_curl_easy_cleanup'
collect2.exe: error: ld returned 1 exit status
mingw32-make[3]: *** [CMakeFiles\sunshine.dir\build.make:530: sunshine.exe] Error 1
mingw32-make[2]: *** [CMakeFiles\Makefile2:177: CMakeFiles/sunshine.dir/all] Error 2
mingw32-make[1]: *** [CMakeFiles\Makefile2:184: CMakeFiles/sunshine.dir/rule] Error 2
mingw32-make: *** [Makefile:188: sunshine] Error 2
```

**Comment by psyke83** [comment]
Check your CmakeCache.txt for these lines:
```
# cat CMakeCache.txt | grep CURL_STATIC
CURL_STATIC_CFLAGS:INTERNAL=-DCURL_STATICLIB
CURL_STATIC_CFLAGS_I:INTERNAL=
CURL_STATIC_CFLAGS_OTHER:INTERNAL=-DCURL_STATICLIB
CURL_STATIC_INCLUDE_DIRS:INTERNAL=
CURL_STATIC_LDFLAGS:INTERNAL=-LD:/Software/msys64/mingw64/lib;-lcurl;-lnghttp2;-lidn2;-lssh2;-lssh2;-lpsl;-lbcrypt;-ladvapi32;-lcrypt32;-lbcrypt;-lssl;-lcrypto;-lssl;-lcrypto;-lgdi32;-lwldap32;-lzstd;-lzstd;-lbrotlidec;-lz;-lws2_32;-LD:/Software/msys64/mingw64/lib;-lidn2;-L/mingw64/lib;-liconv;-L/mingw64/lib;-lunistring;-lbrotlidec;-LD:/Software/msys64/mingw64/lib;-lbrotlicommon
CURL_STATIC_LDFLAGS_OTHER:INTERNAL=
CURL_STATIC_LIBDIR:INTERNAL=
CURL_STATIC_LIBRARIES:INTERNAL=curl;nghttp2;idn2;ssh2;ssh2;psl;bcrypt;advapi32;crypt32;bcrypt;ssl;crypto;ssl;crypto;gdi32;wldap32;zstd;zstd;brotlidec;z;ws2_32;idn2;iconv;unistring;brotlidec;brotlicommon
CURL_STATIC_LIBRARY_DIRS:INTERNAL=D:/Software/msys64/mingw64/lib;D:/Software/msys64/mingw64/lib;/mingw64/lib;/mingw64/lib;D:/Software/msys64/mingw64/lib
CURL_STATIC_LIBS:INTERNAL=
CURL_STATIC_LIBS_L:INTERNAL=
CURL_STATIC_LIBS_OTHER:INTERNAL=
CURL_STATIC_LIBS_PATHS:INTERNAL=
```
If any are missing, it means that your subsequent cmake invocations did not recheck for pkg-config. The solution is to delete the cmakecache.txt before trying to rebuild.

I just rechecked with all packages updated fully, and I can build Sunshine locally without your change.

**Comment by ReenigneArcher** [comment]
Closing as the build issue was due to using `msys2` shell instead of `mingw64` shell.

**Pull request closed without merging**
